### PR TITLE
fix: resubmit button and PR check logic

### LINKED ISSUE #186: preserve directory loc
the loc path should be preserved if:
- user exits the directory selector
- user clicks restore button

if a user opens the change directory, navigates a bit, and closes that menu without selecting a location, the saved directory path should persist. In this case that would be the `loc` path.

### LINKED ISSUE #192: lower case tags
tags are currently being capitalized: `tags: ["Lightning","C-Lightning","Lnd","Wallet","Layer 2"]`

They should be lower cased.

### PR DESCRIPTION
**Pull request by 0tuedon**
Screenshot 2023-10-23 at 15 27 26
Here is how the resubmit button looks.

This closes #192.
Also closes #186

### CODE REVIEW

File: src/pages/api/github/pr.ts [hunk 1]
```diff
@@ -49,6 +49,9 @@ async function pullAndUpdatedPR(
     .catch((err) => {
       throw err;
     });
+  if (pullDetails?.data?.merged) {
+    throw "Your transcript has been merged!";
```
Comment (BalogunofAfrica) [inline src/pages/api/github/pr.ts:53]: I think you might want to throw an error rather than just a plain string

**Comment by 0tuedon** [comment]
This Updated PR close  #192  and #186

**Review by Emmanuel-Develops — COMMENTED** [review]
type Error doesn't have a property of `response`

File: src/components/modals/SubmitTranscriptModal.tsx [hunk 2]
```diff
@@ -83,7 +83,7 @@ const SubmitTranscriptModal = ({ submitState, onClose }: Props) => {
             {isError && !isLoading && (
               <Box>
                 <Text color="gray.400" fontWeight={500}>
-                  Unsucessful
+                  {err?.response?.data?.message || "Unsuccessful"}
```
Comment (Emmanuel-Develops) [inline src/components/modals/SubmitTranscriptModal.tsx:86]: err is returned as Error or null.

read it as `err?.message` instead

**Review by Emmanuel-Develops — CHANGES_REQUESTED** [review]

File: src/components/modals/SubmitTranscriptModal.tsx (hunk 2 above)
Comment (0tuedon) [reply src/components/modals/SubmitTranscriptModal.tsx:86]: So the issue here is Axios extends the  in built error object when returning  the error .when catching the error
so hence any where there is  err?.message on the client side it returns undefined

**Comment by 0tuedon** [comment]
Made an update to fix the errorType issues.

**Review by kouloumos — COMMENTED** [review]
I think that inside the editor we should somehow signal to the user that this is a re-submission. As it is, the experience is exactly the same in the first submit. At least, the "X hours to review and submit" (and later "expired") on the top-left cornet, should be replaced with something else, cause that's not correct. Maybe for starts we could go with the same "Under Review" button that we have at "My Account" page? And also rename the "Submit" button to "Resubmit"?

resubmit

**Comment by kouloumos** [comment]
On another note, I believe that a clean commit history helps a lot with navigating the codebase, finding previous changes, reverting changes, preventing mistakes, etc. The current way that commits are pushed and merged, does not help with that, as for example in this PR, where you have 3 significant changes (resubmit, issue#192 and issue#186 ) you have 5 commits:

- 1st commit: adds the code for resubmit,
- 2nd commit: removes a specific character from the resubmit code added in the 1st commit
- 3rd commit: adds the logic to solve the 2 issues and simultaneously adds a small change to the resubmit code 
- 4th commit: again modifies files that have to do with all the changes and also reverts code that has been added in previous commits.
- 5th commit: again removes the same character that was removed in the 2nd commit, and that was introduced again with the 4th commit

This also makes reviewing more difficult, we should strive for  [atomic commits](https://en.wikipedia.org/wiki/Atomic_commit#Atomic_commit_convention).
[bitcoin-core's contributing guidelines](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md), explain this philosophy very well, see specifically [Committing Patches](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches) and [Squashing Commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits)

File: src/components/sideBarContentEdit/SidebarContentEdit.tsx [hunk 3]
```diff
@@ -130,7 +130,8 @@ const SidebarContentEdit = ({
   };
   const updateTags = (tags: string[]) => {
     const updatedTranscript = getUpdatedTranscript();
-    updatedTranscript.tags = tags;
+    const lowerCaseTags = tags.map((tag) => tag.toLowerCase());
+    updatedTranscript.tags = lowerCaseTags;
```
Comment (kouloumos) [inline src/components/sideBarContentEdit/SidebarContentEdit.tsx:134]: It seems that the logic introduced with 069bef7795a089f3e7738d4f6ecfe36064ae0707 does not solve the problem with the capitalized tags. Looking at the code, we might think that we change the state (in this case `tags`) but in reality, when you click the Submit button, it access a different state which is what it updates the PR with.

This is my understanding of the issue: 
When in the Editor, the state of the metadata (which `tags` is part of) is managed through `sideBarData` which is also accessed through `getUpdatedContent()` and mutated through `sideBarContentUpdater()` which is passed as `updater` to the nested sidebar component in order to be able to change the state of the metadata through the sidebar selection. 

The issue with this new change is that when  `tags` are updated through the dropdown, the updated lowercase value is send to the backend using `saveTranscript()` but `updater()` updates the state with the non-lowercase `tags`. So when `handleSubmit()` reads the state before creating the PR, it reads the state with the non-lowercase `tags`. 

You could just also use the `lowerCaseTags` for the `updater()` but then tags are presented to the user as lowercase which is not what we want. I think that a better solution would be to transform tags to lowercase as closer to the PR-creation as possible, which in this case seems to be here:
https://github.com/bitcointranscripts/transcription-review-front-end/blob/092ad3848e7ce344a2c076957129208ea9710371/src/components/transcript/index.tsx#L221

**Comment by 0tuedon** [comment]
Currently looking into these issues @kouloumos

File: src/components/sideBarContentEdit/SelectDirectory.tsx [hunk 4]
```diff
@@ -220,7 +223,7 @@ const SelectDirectory = ({
             }}
             height={8}
             onChange={handleChange}
-            placeholder={path}
+            placeholder={!isOpen ? updatedTranscript?.loc : path}
```
Comment (kouloumos) [inline src/components/sideBarContentEdit/SelectDirectory.tsx:226]: It seems that the logic introduced with 069bef7795a089f3e7738d4f6ecfe36064ae0707 solves just one of the issues listed in #186. Resetting directory (`loc`) still doesn't work, as it still resets to the current saved state (`content`) and not `originalContent`. It seems that this behavior was wrongly introduced with this line: 
https://github.com/bitcointranscripts/transcription-review-front-end/blob/092ad3848e7ce344a2c076957129208ea9710371/src/components/transcript/index.tsx#L133-L135

File: src/pages/api/github/pr.ts [hunk 5]
```diff
@@ -63,7 +66,7 @@ async function pullAndUpdatedPR(
       owner: forkOwner,
       repo: forkRepo,
       path: `${directoryPath}/${fileSlug}.md`,
-      message: ` "Updated"  "${metaData.fileTitle}" transcript submitted by ${forkOwner}`,
+      message: ` Updated  "${metaData.fileTitle}" transcript submitted by ${forkOwner}`,
```
[the remark this answers is not in the document]
Comment (0tuedon) [reply src/pages/api/github/pr.ts:69]: so instead of `Added "${metaData.fileTitle}" transcript submitted by ${forkOwner}` we have `Added transcript: ${metaData.fileTitle}`??

**Comment by 0tuedon** [comment]
> I think that inside the editor we should somehow signal to the user that this is a re-submission. As it is, the experience is exactly the same in the first submit. At least, the "X hours to review and submit" (and later "expired") on the top-left cornet, should be replaced with something else, cause that's not correct. Maybe for starts we could go with the same "Under Review" button that we have at "My Account" page? And also rename the "Submit" button to "Resubmit"? Another addition could be to change the "fork and create pr" action item in the "Submitting Transcript" list to "updating pr"
> 
> resubmit [ resubmit ](https://user-images.githubusercontent.com/18506343/279330758-bb3cef1b-3914-4764-9859-cecd93736f90.gif) [ ](https://user-images.githubusercontent.com/18506343/279330758-bb3cef1b-3914-4764-9859-cecd93736f90.gif)

So for example if a PR is in review and the time hasn't expired we should only put under review?

**Comment by kouloumos** [comment]
> So for example if a PR is in review and the time hasn't expired we should only put under review?

I am not sure that I understood the question. My understanding of the flow is that as soon as the user/editor opens a PR, we consider the transcript in-review and never expires. So showing "X hours to review and submit" (or "expired" as shown in the video that I uploaded) is not correct.

File: src/components/sideBarContentEdit/SidebarContentEdit.tsx (hunk 3 above)
Comment (Emmanuel-Develops) [reply src/components/sideBarContentEdit/SidebarContentEdit.tsx:134]: We can keep tags always as lowercase, from when we get the data and when we update the data as you have mentioned.

For the user a simple CSS `text-transform: capitalize` will do the capitalization, so tags are always lowercase in our logic.

File: src/components/modals/SubmitTranscriptModal.tsx [hunk 6]
```diff
@@ -35,6 +36,7 @@ type Props = {
 const SubmitTranscriptModal = ({ submitState, onClose }: Props) => {
   const { stepIdx, steps, isLoading, isError, isModalOpen, prResult, err } =
     submitState;
+  const errorMessage = err?.response?.data?.message || err?.message;
```
Comment (Emmanuel-Develops) [inline src/components/modals/SubmitTranscriptModal.tsx:39]: It's easier to manage error as `Error`, if axios returns an Error then in the function that axios is called throw a new Error and pass the axios error message .

File: src/components/transcript/index.tsx [hunk 7]
```diff
@@ -241,7 +241,7 @@ const Transcript = ({ reviewData }: { reviewData: UserReviewData }) => {
         }
       );
     } catch (error) {
-      const err = error as Error;
+      const err = error as AxiosError<{ message: string }>;
```
Comment (Emmanuel-Develops) [inline src/components/transcript/index.tsx:244]: same here

**Review by Emmanuel-Develops — APPROVED** [review]
